version: "3.1"
services:

  postgresdb:
    container_name: petpostgres
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: pet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1qaz2wsx